routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| 
| php artisan vendor:publish --tag=laravel-pagination
|
*/

Auth::routes(['verify' => true]);
Route::view('/{any}', 'spa')->where('any', '.*');
Route::get('/', 'QuestionsController@index');

Route::middleware('verified')->group(function() {

    Route::get('/home', 'HomeController@index')->name('home');
    
    Route::resource('questions', 'QuestionsController')->except('show', 'index');
    // Route::post('/questions/{question}/answers', 'AnswersController@store')->name('answers.store');
    Route::resource('questions.answers', 'AnswersController')->except(['create', 'show']);
    Route::post('/answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');
    
    Route::post('/questions/{question}/favorites', 'FavoritesController@store')->name('questions.favorite');
    Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy')->name('questions.unfavorite');
    
    Route::post('/questions/{question}/vote', 'VoteQuestionController');
    Route::post('/answers/{answer}/vote', 'VoteAnswerController');
    
});

Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::get('/questions', 'QuestionsController@index')->name('questions.index');

app/Answer.php
<?php

namespace App;

use App\Traits\Votable;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use Votable;

    protected $fillable = [
        'body',
        'user_id'
    ];

    protected $appends = [
        'created_date',
        'body_html',
        'is_best'
    ];

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    
    public static function boot()
    {
        parent::boot();
    
        static::created(function($answer) {
            $answer->question->increment('answer_count');
        });

        static::deleted(function($answer) {
            $answer->question->decrement('answer_count');
        });
    }

    public function getBodyHtmlAttribute()
    {
        return clean(\Parsedown::instance()->text($this->body));
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ? 'vote-accepted' : '';
    }

    public function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public function isBest()
    {
        return $this->id === $this->question->best_answer_id ? 'vote-accepted' : '';
    }
}

resources/views/shared/_accept.blade.php
{{-- BEST ANSWER --}}
@can('accept', $model)
    <a href="#" title="Mark this answer as best answer" 
        class="{{ $model->status }} mt-2"
        onclick="event.preventDefault(); document.getElementById('accept-answer-{{ $model->id }}').submit();"
        >
        <i class="fas fa-check fa-2x"></i>
    </a>
    <form action="{{ route('answers.accept', $model->id) }}" method="POST" id="accept-answer-{{ $model->id }}" style="display:none;">
        @csrf
    </form>
@else
    @if ($model->is_best)
        <a href="#" title="The question owner accepted this answer as best answer" 
            class="{{ $model->status }} mt-2"
            >
            <i class="fas fa-check fa-2x"></i>
        </a>
    @endif
@endcan

resources/views/shared/_favorite.blade.php
{{-- FAVORITES --}}
<a href="#" title="Click to mark as favorite question (Click again to undo)" 
    class="favorite mt-2 {{ Auth::guest() ? 'off' : ($model->is_favorited ? 'favorited' : '') }}"
    onclick="event.preventDefault(); document.getElementById('favorite-question-{{ $model->id }}').submit();"
    >
    <i class="fas fa-star fa-2x"></i>
    <span class="favorites-count">{{ $model->favorite_count }}</span>
</a>
<form action="/questions/{{ $model->id }}/favorites" method="POST" id="favorite-question-{{ $model->id }}" style="display:none;">
    @csrf
    @if ($model->is_favorited)
        @method ('DELETE')
    @endif
</form>

resources/views/shared/_vote.blade.php
@if ($model instanceof App\Question)
    @php
        $name = 'question';
        $firstURISegment = 'questions';
    @endphp
@elseif ($model instanceof App\Answer)
    @php
        $name = 'answer';
        $firstURISegment = 'answers';
    @endphp
@endif

@php
    $formId = $name . "-" . $model->id;
    $formAction = "/{$firstURISegment}/{$model->id}/vote";
@endphp
<div class="d-flex flex-column vote-controls">
    {{-- VOTE UP --}}
    <a href="#" title="This {{ $name }} is useful" 
        class="vote-up {{ Auth::guest() ? 'off' : '' }}"
        onclick="event.preventDefault(); document.getElementById('up-vote-{{ $formId }}').submit();"
        >
        <i class="fas fa-caret-up fa-3x"></i>
    </a>
    <form action="{{ $formAction }}" method="POST" id="up-vote-{{ $formId }}" style="display:none;">
        @csrf
        <input type="hidden" name="vote" value="1">
    </form>

    {{-- VOTE COUNT --}}
    <span class="votes-count">{{ $model->vote_count }}</span>

    {{-- VOTE DOWN --}}
    <a href="#" title="This {{ $name }} is not useful" 
        class="vote-down {{ Auth::guest() ? 'off' : '' }}"
        onclick="event.preventDefault(); document.getElementById('down-vote-{{ $formId }}').submit();"
        >
        <i class="fas fa-caret-down fa-3x"></i>
    </a>
    <form action="{{ $formAction }}" method="POST" id="down-vote-{{ $formId }}" style="display:none;">
        @csrf
        <input type="hidden" name="vote" value="-1">
    </form>

    @if ($model instanceof App\Question)
        <favorite :question="{{ $model }}"></favorite>
    @elseif ($model instanceof App\Answer)
        <accept :answer="{{ $model }}"></accept>
    @endif
</div>